/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.wadcorp.catchtable.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class ShopContactChangedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1632587661880689214L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ShopContactChangedEvent\",\"namespace\":\"co.wadcorp.catchtable.event\",\"fields\":[{\"name\":\"shop_id\",\"type\":\"int\"},{\"name\":\"shop_contact\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ShopContactChangedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ShopContactChangedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ShopContactChangedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ShopContactChangedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ShopContactChangedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ShopContactChangedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ShopContactChangedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ShopContactChangedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ShopContactChangedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int shop_id;
  private java.lang.String shop_contact;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ShopContactChangedEvent() {}

  /**
   * All-args constructor.
   * @param shop_id The new value for shop_id
   * @param shop_contact The new value for shop_contact
   */
  public ShopContactChangedEvent(java.lang.Integer shop_id, java.lang.String shop_contact) {
    this.shop_id = shop_id;
    this.shop_contact = shop_contact;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return shop_id;
    case 1: return shop_contact;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: shop_id = (java.lang.Integer)value$; break;
    case 1: shop_contact = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'shop_id' field.
   * @return The value of the 'shop_id' field.
   */
  public int getShopId() {
    return shop_id;
  }

  /**
   * Gets the value of the 'shop_id' field as an Optional&lt;java.lang.Integer&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
   */
  public Optional<java.lang.Integer> getOptionalShopId() {
    return Optional.<java.lang.Integer>ofNullable(shop_id);
  }


  /**
   * Gets the value of the 'shop_contact' field.
   * @return The value of the 'shop_contact' field.
   */
  public java.lang.String getShopContact() {
    return shop_contact;
  }

  /**
   * Gets the value of the 'shop_contact' field as an Optional&lt;java.lang.String&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.String&gt;.
   */
  public Optional<java.lang.String> getOptionalShopContact() {
    return Optional.<java.lang.String>ofNullable(shop_contact);
  }


  /**
   * Creates a new ShopContactChangedEvent RecordBuilder.
   * @return A new ShopContactChangedEvent RecordBuilder
   */
  public static co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder newBuilder() {
    return new co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder();
  }

  /**
   * Creates a new ShopContactChangedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ShopContactChangedEvent RecordBuilder
   */
  public static co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder newBuilder(co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder other) {
    if (other == null) {
      return new co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder();
    } else {
      return new co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ShopContactChangedEvent RecordBuilder by copying an existing ShopContactChangedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ShopContactChangedEvent RecordBuilder
   */
  public static co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder newBuilder(co.wadcorp.catchtable.event.ShopContactChangedEvent other) {
    if (other == null) {
      return new co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder();
    } else {
      return new co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ShopContactChangedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ShopContactChangedEvent>
    implements org.apache.avro.data.RecordBuilder<ShopContactChangedEvent> {

    private int shop_id;
    private java.lang.String shop_contact;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.shop_id)) {
        this.shop_id = data().deepCopy(fields()[0].schema(), other.shop_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.shop_contact)) {
        this.shop_contact = data().deepCopy(fields()[1].schema(), other.shop_contact);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ShopContactChangedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(co.wadcorp.catchtable.event.ShopContactChangedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.shop_id)) {
        this.shop_id = data().deepCopy(fields()[0].schema(), other.shop_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.shop_contact)) {
        this.shop_contact = data().deepCopy(fields()[1].schema(), other.shop_contact);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'shop_id' field.
      * @return The value.
      */
    public int getShopId() {
      return shop_id;
    }

    /**
      * Gets the value of the 'shop_id' field as an Optional&lt;java.lang.Integer&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Integer&gt;.
      */
    public Optional<java.lang.Integer> getOptionalShopId() {
      return Optional.<java.lang.Integer>ofNullable(shop_id);
    }

    /**
      * Sets the value of the 'shop_id' field.
      * @param value The value of 'shop_id'.
      * @return This builder.
      */
    public co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder setShopId(int value) {
      validate(fields()[0], value);
      this.shop_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'shop_id' field has been set.
      * @return True if the 'shop_id' field has been set, false otherwise.
      */
    public boolean hasShopId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'shop_id' field.
      * @return This builder.
      */
    public co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder clearShopId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'shop_contact' field.
      * @return The value.
      */
    public java.lang.String getShopContact() {
      return shop_contact;
    }

    /**
      * Gets the value of the 'shop_contact' field as an Optional&lt;java.lang.String&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.String&gt;.
      */
    public Optional<java.lang.String> getOptionalShopContact() {
      return Optional.<java.lang.String>ofNullable(shop_contact);
    }

    /**
      * Sets the value of the 'shop_contact' field.
      * @param value The value of 'shop_contact'.
      * @return This builder.
      */
    public co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder setShopContact(java.lang.String value) {
      validate(fields()[1], value);
      this.shop_contact = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'shop_contact' field has been set.
      * @return True if the 'shop_contact' field has been set, false otherwise.
      */
    public boolean hasShopContact() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'shop_contact' field.
      * @return This builder.
      */
    public co.wadcorp.catchtable.event.ShopContactChangedEvent.Builder clearShopContact() {
      shop_contact = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ShopContactChangedEvent build() {
      try {
        ShopContactChangedEvent record = new ShopContactChangedEvent();
        record.shop_id = fieldSetFlags()[0] ? this.shop_id : (java.lang.Integer) defaultValue(fields()[0]);
        record.shop_contact = fieldSetFlags()[1] ? this.shop_contact : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ShopContactChangedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ShopContactChangedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ShopContactChangedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ShopContactChangedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.shop_id);

    if (this.shop_contact == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.shop_contact);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.shop_id = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.shop_contact = null;
      } else {
        this.shop_contact = in.readString();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.shop_id = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.shop_contact = null;
          } else {
            this.shop_contact = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










